# Generated by Django 4.2.18 on 2025-06-30 02:58

from django.db import migrations, models
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dead_time',
            field=models.DateTimeField(default=users.models.user.default_dead_time, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_balance',
            field=models.PositiveIntegerField(default=10000000, verbose_name='可用token余额'),
        ),
    ]
