# Generated by Django 4.2.18 on 2025-06-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_alter_application_prologue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='client_ip',
            field=models.CharField(blank=True, default='127.0.0.1', null=True, verbose_name='客户端IP地址'),
        ),
    ]
